name: run k6
on:
  workflow_dispatch:
    inputs:
      scenario_file:
        description: Scenario file inside /scripts
        required: true
        default: test.js
        type: string
      duration:
        description: Duration (in minutes)
        required: true
        default: '1'
        type: string
      vus:
        description: Number of virtual users
        required: true
        default: '1'
        type: string
      extra_cli_args:
        description: Extra CLI args (non secret)
        required: false
        default: ''
        type: string

jobs:
  k6-default:
    name: K6 Run
    uses: ./.github/workflows/test.yml
    with:
      scenario_file: ${{ inputs.scenario_file }}
      duration: ${{ inputs.duration }}
      vus: ${{ inputs.vus }}
