name: "K6 Default Run"
on:
  workflow_call:
    inputs:
      scenario_file:
        required: true
        default: test.js
        type: string
      duration:
        required: true
        default: '1'
        type: string
      vus:
        required: true
        default: '1'
        type: string
      extra_cli_args:
        required: false
        default: ''
        type: string

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: script/${{ inputs.scenario_file }}
          flags: --duration=${{ inputs.duration }}m --vus=${{ inputs.vus }} 
